language: php

php:
- 5.5.9

services:
  - mysql

before_script:
  - mysql -e 'create database schema_test;'
  - composer update
  - composer install --prefer-source --no-interaction --dev

script:
  - vendor/bin/phpunit --configuration phpunit.xml
  - . tests/build/bin/phpcs
  - . tests/build/bin/phpmd

notifications:
  on_success: always
  on_failure: always
